GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Product 1",
  "description": "Description 1",
  "image_url": "http://example.com/image1.jpg",
  "price": 100
}

###
GET http://localhost:3000/orders/2fbee755-c9e3-4503-acec-46ac637d1323
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwODI5MjIxMSwiZXhwIjoxNzA4MjkyMjcxfQ.2AZElurkOrqKk8A7t_QeLRslwJlJMFk3t2xori-lojM

###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwODI5MjIxMSwiZXhwIjoxNzA4MjkyMjcxfQ.2AZElurkOrqKk8A7t_QeLRslwJlJMFk3t2xori-lojM
###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiam9obiIsImlhdCI6MTcwODI5MjEwNCwiZXhwIjoxNzA4MjkyMTY0fQ.3QJDN9RcwCecnoG9m5HWi5Bin6Kr25ZCZ6xHh2DvNJY

POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDgyOTIwNDMsImV4cCI6MTcwODI5MjEwM30.kp9lQufx2Epd9T5Ayc6ZJT-s_L-QidqALm93xyuOfZE

{
  "items": [
    {
      "product_id": "0002a704-8650-4e15-aeb5-88fc1b2e921c",
      "quantity": 4
    },
      {
      "product_id": "04c4353a-3f6d-4272-a8f2-44b82c05ecc0",
      "quantity": 2
    }
  ],
  "card_hash": "4242424242424242"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "john",
  "password": "changeme"
}
